project:
  type: book
  post-render: 
    # - quarto render --profile slides
    - quarto render slides/
    - quarto render thesis/
    - quarto render manuscript/

filters:
  # - at: pre-quarto
  #   path: ../filters/abstract-section.lua
  #   # moves abstract section to meta data so it does not need
  #   # to to in metadata. Just put it in an "# Abstract" section    # same as any other section
  - at: post-quarto
    path: ./filters/captions.lua
    
execute:
  freeze: auto
  echo: true
      
format:
  html:
    theme: 
      - default
      - .custom.scss
    toc-depth: 2
    notebook-links: true
    number-sections: false  
    reference-location: margin
    mermaid:
      theme: neutral

comments:
  hypothesis: true

lightbox: true

book:
  repo-url: "https://github.com/munch-group/projectname"
  repo-actions: [edit, issue, source]  
  title: "projectname"
  author: "Joanna Doh"  
  sidebar:
    collapse-level: 1
    search: true  
  chapters:
    - index.qmd
    - part: "Manuscript"
      chapters:
      # (the same files must be listed _quarto-slides.yml to render as slides)
      - manuscript/index.qmd 
    - part: "Thesis"
      chapters:
      # (the same files must be listed _quarto-slides.yml to render as slides)
      - thesis/index.qmd 
    - part: "Slides"
      chapters:
      # (the same files must be listed _quarto-slides.yml to render as slides)
      - slides/index.qmd 
    - part: "Notebooks"
      chapters: 
      - notebooks/example.ipynb
    - part: "Workflows"
      chapters: 
      - workflow.py
    - part: "Reports"
      chapters: 
      - reports/example.qmd
    # - part: "Tables"
    #   chapters: 
    #   - tables/example.ipynb
  downloads: [pdf]
     
bibliography: references.bib

