project:
  type: book
  post-render: 
    - quarto render --profile slides

execute:
  freeze: auto
  echo: true

format:
  html:
    theme: 
      - default
      - custom.scss
    toc-depth: 2
    notebook-links: global
    number-sections: false
  pdf:
    documentclass: scrbook
    papersize: a4
    highlight-style: kate 
    fig-width: 7
    fig-height: 5
    toc-depth: 2
    header-includes: # for resetting numbers in each part so the pdf report sections begins with one
      - \makeatletter
      - \@addtoreset{chapter}{part}
      - \makeatother     
    # include-in-header:
    #   - file: header_extra.tex

comments:
  hypothesis: true

book:
  repo-url: "https://github.com/munch-group/projectname"
  repo-actions: [edit, issue, source]  
  title: "projectname"
  author: "Joanna Doh"  
  chapters:
    - index.qmd
    - workflow.py
    - workflow_notebooks.py    
    - part: "Notebooks"
      chapters: 
      - notebooks/example.ipynb
    - part: "Reports"
      chapters: 
      - reports/example.qmd
    - part: "Tables"
      chapters: 
      - tables/example.qmd
    - part: "Slides"
      chapters:
      # (the same files must be listed _quarto-slides.yml to render as slides)
      - slides/example.qmd 
  downloads: [pdf]
     
bibliography: references.bib
