project:
  type: manuscript
  output-dir: ../_book/thesis

manuscript:
  article: index.qmd

format:
  html: default
  docx: default
  jats: default
  pdf:
    documentclass: scrbook
    pdf-engine: pdflatex
    papersize: A4
    # sansfont: Helvetica
    toc: true
    toc-depth: 2
    toc-title: "Table of contents"
    # lof: true
    # lot: true    
    geometry:
      - right=2.54cm   
      # - inner=3cm
      # - outer=4cm
      # - top=3cm
      # - bottom=4cm
      # - headsep=22pt
      # - headheight=11pt
      # - footskip=33pt
      # - ignorehead
      # - ignorefoot
      # - heightrounded
    # linestretch: 1.25 
    # mainfont: "Times New Roman"
    # sansfont: "Arial"
    # monofont: "Courier New"
    # mathfont: "TeX Gyre Termes Math"             
    number-sections: true
    # number-depth: 2    
    highlight-style: kate 
 
    include-in-header:
      - file: header_extra.tex
    template-partials:
      - before-body.tex      

notebook-links: false

execute:
  freeze: auto

bibliography: ../references.bib